# Generated by Django 5.0.6 on 2026-06-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de alerta',
                'verbose_name_plural': 'Configuraciones de alertas',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TONER_BAJO', 'Tóner bajo'), ('TONER_CRITICO', 'Tóner crítico'), ('CUOTA_EXCEDIDA', 'Cuota mensual excedida'), ('CONTRATO_POR_VENCER', 'Contrato por vencer'), ('CONTRATO_VENCIDO', 'Contrato vencido')], max_length=25)),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='ACTIVA', max_length=10)),
                ('equipo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('equipo_nombre', models.CharField(blank=True, max_length=200)),
                ('equipo_serial', models.CharField(blank=True, max_length=100)),
                ('cliente_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('contrato_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contrato_numero', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.CharField(blank=True, max_length=150)),
                ('nota_resolucion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'nivel'], name='alertas_ale_estado_84a3a7_idx'), models.Index(fields=['equipo_id'], name='alertas_ale_equipo__c60509_idx'), models.Index(fields=['cliente_id'], name='alertas_ale_cliente_d5af69_idx')],
            },
        ),
    ]
